mediumapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    # path('articles/', include('articles.urls'))

]

pages/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('articles.urls')),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('membership/', views.membership_page, name='membership'),
    path('terms/', views.terms_page, name='terms'),
    path('privacy/', views.privacy_page, name='privacy'),
    path('help/', views.help_page, name='help'),
    path('follows/<int:pk>', views.following, name='follows'),
    path('followers/<int:pk>', views.followers, name='followers'),

   
]

articles/forms.py
from .models import Article
from django import forms

class ArticleCreateForm(forms.ModelForm):
    title = forms.CharField( widget=forms.TextInput (attrs={
        'placeholder': 'Title',
        # 'value': 'giig'
        

    }))
    body = forms.CharField (label='', widget=forms.Textarea (attrs={
        'class': 'article-create-form-body', 
        'placeholder': 'Tell your story...',
    

    }))
    class Meta:
        model = Article
        fields = [
            'title', 
            'body'
        ]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} About page {% endblock %}


{% block story %}
<li class="navlink"><a href="#"><u>Our story</u></a></li>
{% endblock story %}

{% block nav %}
<nav class="about-nav">
    {% endblock nav %}

    {% block content %}

    <div class="about-container1">
        <div class="about-container1-text">
            <h1>Every idea needs a</h1>
            <div class="about-container1-subtext">
                <img class="about-medium-logo" src="{% static 'images/Medium.png' %}" alt="">
                <h2>.</h2>
            </div>
        </div>
    </div>
    <div class="about-container2">
        <div class="about-container2-col1">
            <h4>The best ideas can change who we are. Medium is where those ideas take shape, take off, and spark
                powerful conversations. We’re an open platform where over 100 million readers come to find insightful
                and dynamic thinking. Here, expert and undiscovered voices alike dive into the heart of any topic and
                bring new ideas to the surface. Our purpose is to spread these ideas and deepen understanding of the
                world.
                <br><br>
                We’re creating a new model for digital publishing. One that supports nuance, complexity, and vital
                storytelling without giving in to the incentives of advertising. It’s an environment that’s open to
                everyone but promotes substance and authenticity. And it’s where deeper connections forged between
                readers and writers can lead to discovery and growth. Together with millions of collaborators, we’re
                building a trusted and vibrant ecosystem fueled by important ideas and the people who think about them.
            </h4>
        </div>
        <div class="about-container2-col2">
            <video width='90%' height='90%' autoplay loop>
                <source src="{% static 'videos/globe1.mp4' %}">
                Your browser does not support the video tag.
            </video>
        </div>
    </div>
    <div class="about-container3">
        <div class="about-container3-col1">
            <h2>A living network of curious minds.</h2>
            <div class="about-container3-text">
                <p>Anyone can write on Medium. Thought-leaders, journalists, experts, and individuals with unique
                    perspectives share their thinking here. You’ll find pieces by independent writers from around the
                    globe, stories we feature and leading authors, and smart takes on our own suite of blogs and
                    publications.</p>
            </div>
        </div>
    </div>
    <div class="about-container4">
        <div class="about-container4-sub">
            <div class="about-container4-col">
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="last-link" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}" alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
            </div>
            <div class="about-container4-col">
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="last-link" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}" alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
            </div>
            <div class="about-container4-col">
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="about-container4-links" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}"
                        alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
                <a class="last-link" href="{% url 'login' %}"><img src="{% static 'images/user.png' %}" alt="">
                    <div>
                        <h4>Musa Gerald</h4>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="about-container5">
        <div class="about-container5-col1">
            <h2>Over 100 million readers and growing.</h2>
        </div>
        <div class="about-container5-col2">
            <div class="about-container5-col2-1">
                <img src="{% static 'images/me.JPG' %}" alt="">
                <div class="color-circle">
                    <div class="color-circle1"></div>
                    <div class="color-circle2"></div>
                </div>
            </div>
            <div class="about-container5-col2-2">
                <h4>"There’s no other place that combines such an excellent level of writing with a truly engaged and
                    active community. Medium is truly where ideas are born, shared, and spread."</h4>
                <p>Joel Leon</p>
            </div>
        </div>
    </div>
    <div class="about-container6">
        <div class="about-container6-sub">
            <h2>Create the space for your thinking to take off.</h2>
            <div class="about-container6-p">
                <p>A blank page is also a door. At Medium you can walk through it. It's easy and free to share your
                    thinking on any topic, connect with an audience, express yourself with a range of publishing tools,
                    and even earn money for your work.</p>
            </div>
            <div class="about-container6-btn"><a href=""><button>Write on Medium</button></a></div>
        </div>
    </div>
    <div class="about-container7">
        <div class="about-container7-sub">
            <h2>Get more with membership.</h2>
            <div class="about-container7-p">
                <p>Become a Medium member to enjoy unlimited access and directly support the writers you read most.</p>
            </div>
            <div class="about-container7-btn"><a href=""><button>See membership options</button></a></div>
        </div>
    </div>
    <div class="about-container8">
        <div class="about-container8-sub1">
            <h3>Read as much as you want.</h3>
            <img width="50%" height="35%" src="{% static 'images/m2.png'%}" alt="">
            <div class="about-container8-sub-container">
                <p>Enjoy unlimited access to every story across all of your devices.</p>
            </div>
        </div>
        <div class="about-container8-sub1">
            <h3>Reward quality content.</h3>
            <img width="50%" height="35%" src="{% static 'images/m1.png' %}" alt="">
            <div class="about-container8-sub-container">
                <p>Your membership helps us pay writers, and keeps your experience ad-free.</p>
            </div>
        </div>
    </div>
    <div class="about-container9">
        <div class="about-container9-sub1">
            <h2>Take Medium with you.</h2>
            <div class="about-container9-sub-1">
                <div class="about-container9-sub-1-1">
                    <p>Download our app so you can read wherever you are.</p>
                </div>
                <div class="about-container9-sub-1-2">
                    <a href=""><img height="100%" width="100%" src="{% static 'images/appstore.png' %}" alt=""></a>
                    <a href=""><img height="100%" width="100%" src="{% static 'images/playstore.png' %}" alt=""></a>
                </div>
            </div>
        </div>
        <div class="about-container9-sub2">
            <img height="85%" width="60%" src="{% static 'images/phone.png' %}" alt="">
        </div>
    </div>
    <div class="about-container10">
        <div class="about-container10-sub1">
            <h2>Learn more about us. Or join us.</h2>
        </div>
        <div class="about-container10-sub2">
            <div class="about-container10-sub2-i">
                <div class="about-container10-sub2-i-div">
                    <h3>The Medium blog</h3>
                    <p>Visit our company blog for the latest news, product updates, and tips and tricks.</p>
                </div>
                <a href=""><button>Read our blog</button></a>
            </div>
            <div class="about-container10-sub2-ii">
                <div class="about-container10-sub2-ii-div">
                    <h3>Work at Medium</h3>
                    <p>Our team is home to engineers, journalists, artists, and creatives of all stripes.</p>
                </div>
                <a href=""><button>View open positions</button></a>
            </div>
        </div>
    </div>
    <div class="about-container11">
        <div class="about-container11-sub1">
            <video width='100%' height='100%' autoplay loop>
                <source src="{% static 'videos/cube.mp4' %}">
            </video>
        </div>
        <div class="about-container11-sub2">
            <h3>Read, write, and expand your world.</h3>
            <a href=""><button>Get Started</button></a>
        </div>
    </div>
    <div class="about-container12">
        <a href="">
            <img src="{% static 'images/Medium.png' %}" alt="">
        </a>
    </div>
   
    <footer class="about-footer">
        <div class="footer-container">
            <ul>
                <li><a href="{% url 'terms' %}">Terms</a></li>
                <li><a href="{% url 'privacy' %}">Privacy</a></li>
                <li><a href="{% url 'help' %}">Help</a></li>
            </ul>
        </div>
    </footer>
    {% endblock content %}

templates/article_create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Create article {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lexend Deca"> -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source Serif 4"> -->
</head>

<body>
    <form class="article-create-form" action="" method="POST">{% csrf_token %}
        <nav class="article-create-nav">
            <div class="article-create-nav-container">
                <div class="article-create-div1">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'images/medium-short.png' %}" height="40%" width="22%" alt="medium-logo">
                    </a>
                    {% if user.username == 'admin' %}
                    <p>Draft in {{user.username|capfirst}}</p>
                    {% else %}
                    <p>Draft in {{user.first_name}} {{user.last_name}}</p>
                    {% endif %}
                </div>
                <div class="article-create-div2">
                    <input type="submit" value="Publish">
                    <h2 class="dot3"><a href="">&#9679;&#9679;&#9679;</a></h2>
                    <div class="article-create-div2-i">
                        <a class="bell" href=""><img src="{% static 'images/notification.png' %}" alt=""></a>
                        {% if user.username == 'admin' %}
                        <a class="email-icon" href="">{{user.username|slice:1|capfirst}}</a>
                        {% else %}
                        <a class="email-icon" href="">{{user.first_name|slice:1}}</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>
        <main class="article-create-main">
            <div class="article-create-main-div">
                <p class="article-create-form-title">
                    <input type="text" name="title"  placeholder="Title" required=""
                        id="id_title">
                </p>
                <p class="article-create-form-body">
                    <textarea name="body" 
                        placeholder="Tell your story..." required="" style="height: 500%;" id="id_body"></textarea>
                </p>
            </div>
        </main>
        <!-- <footer class="article-create-footer">
            <p>this is article create footer</p>
        </footer> -->
    </form>
</body>

templates/article_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home Page{% endblock title %}

{% block nav %}
<nav class="detail-nav">
    {% endblock nav %}

    {% block content %}
    <!-- {% if user.is_authenticated %} -->
    <div class="home-body">
        <div class="home-main">
            <!-- <br>
        <div class="hi-text">Welcome &nbsp; <b>{{user.username}}</b>. Here are your reads.</div> -->

            <div class="article-home-container">
                <div class="article-detail-container">
                    {% if user == detail.author %}
                    <div class="update">
                        <a class="update-btn" href="{% url 'update' detail.pk %}"><button type="submit">Edit
                                Article</button></a>
                        <a class="update-btn1" href="{% url 'delete' detail.pk %}"><button class="button"
                                type="submit">Delete
                                Article</button></a>
                    </div>
                        {% if detail.author.profile %}
                        <a class="detail-a" href="{% url 'profile' detail.author.profile.pk %}">
                            <img class="detail-img" src="{% static 'images/me.jpg' %}" width="8%" height="100%"
                                alt="">&nbsp;
                            <p>{{detail.author}} &nbsp;|&nbsp; {{detail.publish}}</p>
                        </a>
                        {% else %}
                        <a class="detail-a" href="{% url 'no_profile' %}">
                            <img class="detail-img" src="{% static 'images/me.jpg' %}" width="8%" height="100%"
                                alt="">&nbsp;
                            <p>{{detail.author}} &nbsp;|&nbsp; {{detail.publish}}</p>
                        </a>
                        {% endif %}
                    <h2><a href="">{{detail.title}}</a></h2>
                    <p><a href="">{{detail.body|safe}}</a></p>
                    {% else %}
                    {% if detail.author.profile %}
                    <a class="detail-a" href="{% url 'profile' detail.author.profile.pk %}">
                        <img class="detail-img" src="{% static 'images/me.jpg' %}" width="8%" height="100%"
                            alt="">&nbsp;
                        <p>{{detail.author}} &nbsp;|&nbsp; {{detail.publish}}</p>
                    </a>
                    {% else %}
                    <a class="detail-a" href="{% url 'no_profile' %}">
                        <img class="detail-img" src="{% static 'images/me.jpg' %}" width="8%" height="100%"
                            alt="">&nbsp;
                        <p>{{detail.author}} &nbsp;|&nbsp; {{detail.publish}}</p>
                    </a>
                    {% endif %}
                    <h2><a href="">{{detail.title}}</a></h2>
                    <p><a href="">{{detail.body|safe}}</a></p>
                    {% endif %}
                </div>

            </div>
            <div class="like-comment-container">
                <a href="{% url 'like-article' detail.pk %}" id="like-btn" value="{{ detail.id}}"><img
                        src="{% static 'images/hands.png' %}" alt=""></a>{{total}}&nbsp;&nbsp;&nbsp;<a id="like-btn"
                    value="{{ detail.id }}"><img src="{% static 'images/chat1.png' %}" alt=""></a>0&nbsp;&nbsp;&nbsp; <a
                    id="like-btn">&#9679;&#9679;&#9679;</a>
            </div>
        </div>


        <div class="home-sidebar">
            <h2>Staff picks</h2>

        </div>
    </div>
    <!-- {% else %}
<p align="center" style="font-size: large; font-weight: bold; padding: 5px;">You are not logged in</p> -->
    <!-- <p class="home-login"><a id="home-login" href="{% url 'login' %}"> Login</a></p> -->
    <!-- <div class="home-img">
    <img src="{% static 'images/home.png' %}" height="100%" width="100%" alt="">
</div> -->
    <!-- {% endif %} -->

    {% endblock content %}

templates/article_update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Edit article {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lexend Deca"> -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source Serif 4"> -->
</head>

<body>
    <form class="article-create-form" action="" method="POST">{% csrf_token %}
        <nav class="article-create-nav">
            <div class="article-create-nav-container">
                <div class="article-create-div1">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'images/medium-short.png' %}" height="40%" width="22%" alt="medium-logo">
                    </a>
                    {% if user.username == 'admin' %}
                    <p>Draft in {{user.username|capfirst}}</p>
                    {% else %}
                    <p>Draft in {{user.first_name}} {{user.last_name}}</p>
                    {% endif %}
                </div>
                <div class="article-create-div2">
                    <input type="submit" value="Update">
                    <h2 class="dot3"><a href="">&#9679;&#9679;&#9679;</a></h2>
                    <div class="article-create-div2-i">
                        <a class="bell" href=""><img src="{% static 'images/notification.png' %}" alt=""></a>
                        {% if user.username == 'admin' %}
                        <a class="email-icon" href="">{{user.username|slice:1|capfirst}}</a>
                        {% else %}
                        <a class="email-icon" href="">{{user.first_name|slice:1}}</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>
        <main class="article-create-main">
            <div class="article-create-main-div">
                <p class="article-create-form-title">
                    <input type="text" name="title"  placeholder="Title" required=""
                        id="id_title" value="{{form.instance.title}}">
                </p>
                <p class="article-create-form-body">
                    <textarea name="body" 
                        placeholder="Tell your story..." style="height: 1000%; width:100%" required="" id="id_body">{{form.instance.body}}</textarea>
                </p>
                <!-- {{form.as_p}} -->
            </div>
        </main>
        <!-- <footer class="article-create-footer">
            <p>this is article create footer</p>
        </footer> -->
    </form>
</body>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Medium App {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lexend Deca"> -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source Serif 4"> -->
</head>

<body>
    {% block nav %}
    <nav>
    {% endblock nav %}
        <div class="nav-bar">
            <div class="sub-nav-bar">
                {% block medium_logo %}
                <div class="logo"><a href="{% url 'home' %}"><img src="{% static 'images/Medium-logo.png' %}"
                            alt="medium-logo"></a>
                </div>
                {% endblock medium_logo %}
                <div class="nav-options">
                    <ul>
                        {% block story %}
                        <li class="navlink"><a href="{% url 'about' %}">Our story</a></li>
                        {% endblock story %}
                        {% block membership %}
                        <li class="navlink"><a href="{% url 'membership' %}">Membership</a></li>
                        {% endblock membership%}
                        <li class="navlink"><a href="{% url 'create' %}">Write</a></li>
                        {% if user.is_authenticated %}
                        <li class="navlink"><a href="{% url 'logout' %}">Sign out</a></li>
                        {% else %}
                        {% block signin %}
                        <li class="navlink"><a href="{% url 'login' %}">Sign in</a></li>
                        {% endblock signin %}
                        {% endif %}
                    </ul>
                    {% block btn1 %}
                    {% if user.is_authenticated %}
                    <a href="" class="btn1">Get started</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn1">Get started</a>
                    {% endif %}
                    {% endblock btn1 %}
                </div>

            </div>
        </div>
    </nav>
    <main>
        {% block content %}
       
        {% endblock content %}
    </main>
    
    
</body>

</html>

templates/followers.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% if profile.user.username == 'admin' %}
    <br><h1>{{profile.user.username | capfirst}}'s Followers</h1><br>
{% else %}
    <br><h1>{{profile.user.first_name | capfirst}} {{profile.user.last_name | capfirst}}'s Followers</h1><br>
{% endif %}
{% for followers in profile.followed_by.all %}
<u1>
    <li><a  href="{% url 'profile' followers.pk %}">{{followers}}</a></li>
</u1>
{% endfor %}

{% endblock content %}

templates/follows.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% if profile.user.username == 'admin' %}
    <br><h1>{{profile.user.username | capfirst}} Follows</h1><br>
{% else %}
    <br><h1>{{profile.user.first_name | capfirst}} {{profile.user.last_name | capfirst}} Follows</h1><br>
{% endif %}
    
{% for following in profile.follows.all %}
<u1>
    <li><a href="{% url 'profile' following.pk %}">{{following}}</a></li>
</u1>
{% endfor %}

{% endblock content %}

templates/help.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Help page {% endblock %}

{% block content %}
<div class="terms-container1">
    <h2>Need Help?.</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad quis non placeat at ipsa corrupti, iusto, dolore veritatis voluptatibus, omnis voluptas repellat maxime provident! Tempore maiores debitis quidem reprehenderit omnis.
    Sunt in cumque itaque, eligendi aliquam obcaecati ea minus, quidem fugiat molestias nulla repellat. Excepturi distinctio nemo dolore ut eaque nam hic dignissimos magnam quidem libero consequuntur ab, fugit totam.
    Necessitatibus ea dignissimos nam? Minima porro eligendi vitae sed iusto suscipit cupiditate, nesciunt animi quos maiores nostrum doloribus optio officia architecto quis pariatur ea eveniet sapiente. Dicta nam sapiente molestias!
    Ea exercitationem iure cum explicabo excepturi et harum facilis facere dolorem repellat veritatis laborum voluptatem sunt voluptas necessitatibus repudiandae quaerat perferendis ab, rem doloremque architecto earum, vitae dicta. Accusantium, maiores!
    Iure corporis asperiores nisi nesciunt error nostrum nulla illum expedita provident, vitae repellendus ipsa voluptas perferendis sunt atque possimus suscipit. Ipsum eaque, doloremque quibusdam voluptatibus quae aliquid sit officia optio.
    Nobis molestiae quibusdam consequuntur consequatur nisi, nulla eveniet labore, magnam suscipit repellat quidem in tempora fugiat debitis nihil. Est corrupti reiciendis repellat in quam quos cumque eligendi blanditiis voluptate architecto?</p>
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home Page{% endblock title %}

{% block nav %}
<nav class="detail-nav">
    {% endblock nav %}

    {% block content %}
    {% if user.is_authenticated %}
    <div class="home-body">
        <div class="home-main">
            <br>
            <div class="hi-text">Welcome &nbsp; <b>{{user.username}}</b>. Here are your reads.</div>
            {% for articles in article_list %}
            <div class="home-container">
                <div class="article-container">
                    <a href="{% url 'profile' articles.author.profile.id %}"><img src="{% static 'images/me.jpg' %}" width="4%" height="100%" alt="">&nbsp;
                        <p>{{articles.author}} &nbsp;|&nbsp; {{articles.publish}}</p>
                    </a>
                    <h2><a class="article-title" href="{% url 'detail' articles.pk %}">{{articles.title}}</a></h2>
                    {% if articles.body|length > 400 %}
                    <p><a href="{% url 'detail' articles.pk %}">{{articles.body|slice:400|safe}}</a></p>
                    {% else %}
                    <p><a href="{% url 'detail' articles.pk %}">{{articles.body|safe}}</a></p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="home-sidebar">
            <h2>Staff picks</h2>
        </div>
    </div>
    {% else %}
    <p align="center" style="font-size: large; font-weight: bold; padding: 5px;">You are not logged in</p>
    <!-- <p class="home-login"><a id="home-login" href="{% url 'login' %}"> Login</a></p> -->
    <div class="home-img">
        <img src="{% static 'images/home.png' %}" height="100%" width="100%" alt="">
    </div>
    {% endif %}

    {% endblock content %}

templates/no_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} No Profile {% endblock title %}

{% block nav %}
<nav class="detail-nav">
    {% endblock nav %}

    {% block content %}

    <div id="profile-home-body">
        <div id="profile-main">
            <div id="profile-main-container1">
                <h1>You don't have a Profile</h1>
                <div id="profile-home-about-container">
                    <!-- <div id="profile-home-about-container-link">
                        <a href="" id="profile-home-link">Home</a><a href="">About</a>
                    </div> -->
                </div>

            </div>

        </div>
        <div id="profile-side"></div>
    </div>
    {% endblock content %}

templates/privacy.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Privacy page {% endblock %}

{% block content %}
<div class="terms-container1">
    <h2>Our Privacy Policy.</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad quis non placeat at ipsa corrupti, iusto, dolore veritatis voluptatibus, omnis voluptas repellat maxime provident! Tempore maiores debitis quidem reprehenderit omnis.
    Sunt in cumque itaque, eligendi aliquam obcaecati ea minus, quidem fugiat molestias nulla repellat. Excepturi distinctio nemo dolore ut eaque nam hic dignissimos magnam quidem libero consequuntur ab, fugit totam.
    Necessitatibus ea dignissimos nam? Minima porro eligendi vitae sed iusto suscipit cupiditate, nesciunt animi quos maiores nostrum doloribus optio officia architecto quis pariatur ea eveniet sapiente. Dicta nam sapiente molestias!
    Ea exercitationem iure cum explicabo excepturi et harum facilis facere dolorem repellat veritatis laborum voluptatem sunt voluptas necessitatibus repudiandae quaerat perferendis ab, rem doloremque architecto earum, vitae dicta. Accusantium, maiores!
    Iure corporis asperiores nisi nesciunt error nostrum nulla illum expedita provident, vitae repellendus ipsa voluptas perferendis sunt atque possimus suscipit. Ipsum eaque, doloremque quibusdam voluptatibus quae aliquid sit officia optio.
    Nobis molestiae quibusdam consequuntur consequatur nisi, nulla eveniet labore, magnam suscipit repellat quidem in tempora fugiat debitis nihil. Est corrupti reiciendis repellat in quam quos cumque eligendi blanditiis voluptate architecto?</p>
</div>

{% endblock content %}